server:
  port: 8515

spring:
  application:
    name: fund-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
  datasource:
    url: jdbc:mysql://124.223.50.35:3307/finance?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
logging:
  level:
    com.hdu: debug
  pattern:
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      update-strategy: not_null
      id-type: auto

knife4j:
  enable: true
  openapi:
    title: 基金平台接口文档
    description: "基金平台接口文档"
    concat: vvc
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hdu.finance.controller
