server:
  port: 8516
spring:
  application:
    name: customer-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
  datasource:
    url: jdbc:mysql://124.223.50.35:3307/finance?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #spring:
  redis:
    host: 124.223.50.35
    port: 6379
    database: 0
    password: asdfghjkl #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
logging:
  level:
    com.hdu: debug
  pattern:
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      update-strategy: not_null
      id-type: auto

knife4j:
  enable: true
  openapi:
    title: 基金平台接口文档
    description: "基金平台接口文档"
    concat: vvc
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hdu.customer.controller
